export enum LayoutConfigurationFormEnum {
  FORM_ID = "form-id",
  THEME_CONFIGURATION_ID = "widgetThemeData",
  TEASER_CONFIGURATION_ID = "widgetTeaser",
  REPLY_CONFIGURATION_ID = "widgetInputPlaceholder",
  HOTSPOT_ICON_CONFIGURATION_ID = "widgetHotspotIcon",
  JUMP_CONFIGURATION_BACKGROUND = "btnPrimaryBackgroundColor",
  JUMP_CONFIGURATION_COLOR = "btnPrimaryColor",
  HOTSPOT_CONFIGURATION_BACKGROUND = "hotspotButtonColor",
  CLOSE_CONFIGURATION_COLOR = "closeButtonColor",
  HEADER_CONFIGURATION_GRADIENT_FIRST_COLOR = "headerBackgroundColor1",
  HEADER_CONFIGURATION_GRADIENT_SECOND_COLOR = "headerBackgroundColor2",
  HEADER_CONFIGURATION_COLOR = "headerTextColor",
  GENERIC_LINK_COLOR = "linkColor",
  GENERIC_USER_SAYS_TEXT_COLOR = "userSaysTextColor",
  GENERIC_USER_SAYS_BACKGROUND_COLOR = "userSaysBackgroundColor",
  GENERIC_BOT_SAYS_TEXT_COLOR = "botSaysTextColor",
  GENERIC_BOT_SAYS_BACKGROUND_COLOR = "botSaysBackgroundColor",
  GENERIC_MAIN_TEXT_COLOR = "mainTextColor",
  GENERIC_MESSAGE_SEND_BTN_COLOR = "messageSendBtnColor",
}
