export enum RoutesKeysEnum {
  HOME = "HOME",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  DEFAULT = "DEFAULT",
  DASHBOARD = "DASHBOARD",
  DEPLOY = "DEPLOY",
  INTENTS = "INTENTS",
  CREATE_INTENT = "CREATE_INTENT",
  SETTINGS = "SETTINGS",
  KEYWORDS = "KEYWORDS",
  IMPROVE = "IMPROVE",
  TRAP = "TRAP",
}
